# Generated by Django 5.0.4 on 2024-04-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="model1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2000)),
                ("description", models.CharField(max_length=200000)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
