# Generated by Django 5.0.4 on 2024-05-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insta_clone_app", "0002_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
