# Generated by Django 5.0.4 on 2024-05-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insta_clone_app", "0003_alter_photo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="Title",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
